efficientgo/e2e

matchers/matcher.go
matchers/regexp.go
metrics.go

Signed-off-by: Matej Gera <matejgera@gmail.com>
Since `matchers` are currently internal package, it cannot be used when importing `e2e` and thus making it not possible to use matchers for metrics option.
Resolves #7.

Move Matchers pkg from internal

---

env.go
env_docker.go

Signed-off-by: Matej Gera <matejgera@gmail.com>
Currently the `Start` method for a Docker runnable is checking for the container readiness straight away. However, in case the Docker image is not available locally, it has to be downloaded first, which can also take considerable time and can cause the readiness-check loop to time out. This PR adds a separate step in the process to check whether the image is available, and if not, to wait for it to download.
Resolves #3

Docker runnable start: Wait for image download if not available

---

instrumented.go
instrumented_test.go
metrics.go

Signed-off-by: Matej Gera <matejgera@gmail.com>
Right now, the `WaitSumMetrics` uses whichever backoff configuration is currently used for the instrumented runnable. However, this might not be suitable for all cases - in some scenarios, user's might want to configure this to e.g. have increased backoffs or to have more retries.
This change adds a new option to configure the backoff for `WaitSumMetrics`. If not set, the default is used.

WaitSumMetrics: Add option to configure backoff

---

db/db.go
db/prometheus.go
db/thanos.go
env.go
env_docker_ext_test.go
instrumented.go
instrumented_composite.go
instrumented_test.go
monitoring/monitoring.go

Signed-off-by: Bartlomiej Plotka <bwplotka@gmail.com>

Refactored instrumented for more consistent API with runnable.

---

db/db.go

`NewMinio` relies on the KES implementation hosted at https://play.min.io:7373
It looks like the components had diverged. We noticed this with failed CI in one of our components which was rectified in https://github.com/observatorium/api/pull/251
This updates the tag and the corresponding required change for the command.

db: Update minio version and bin path

---

db/db.go

Currently, `NewMinio` always runs minio with SSE-S3 enabled using KMS as defined in https://docs.min.io/docs/minio-kms-quickstart-guide.html. 
This results in dependency on both GitHub (for key and cert) and https://play.min.io:7373, just to start minio container for any e2e test as discussed in https://github.com/observatorium/rules-objstore/pull/9#discussion_r840588813. The test also cannot be run without active net connection.
SSE-S3 encryption for minio isn't commonly used for e2e tests for eg in [Thanos](https://github.com/thanos-io/thanos/blob/9ec283dbea39be1708401eed2830e40a05f6d46a/test/e2e/e2ethanos/services.go#L1024) and [Observatorium API](https://github.com/observatorium/api/blob/main/test/e2e/configs.go#L177), so this PR makes it optional with the default being SSE turned …

Make minio SSE using KMS optional

---

env_docker.go

Problem: Explicit download of images fail if you build local image with tag that fakes some upstream image.
Signed-off-by: Bartlomiej Plotka <bwplotka@gmail.com>

Fixed support for local images.

---

instrumented.go
instrumented_composite.go
instrumented_test.go

When using `WaitSumMetricsWithOptions` together with the `WaitMissingMetrics` option it now counts towards the metrics backoff, which eventually will stop the wait instead of looping forever.
Fixes #38.

Fix infinite loop on waiting for metrics

---

monitoring/monitoring.go

[v0.45.0](https://console.cloud.google.com/gcr/images/cadvisor/global/cadvisor@sha256:9360d7421c5e9b646ea13e5ced3f8e6da80017b0144733a04b7401dd8c01a5cb/details?tab=pull) is a multi-arch image manifest. 
[v0.44.0](https://console.cloud.google.com/gcr/images/cadvisor/GLOBAL/cadvisor@sha256:ef1e224267584fc9cb8d189867f178598443c122d9068686f9c3898c735b711f/details?tag=v0.44.0&tab=pull) is only x86_64.

Upgrade cadvisor to multi-arch image

---

env_docker.go

`host.docker.internal` is the recommended option according to [Docker's docs](https://docs.docker.com/desktop/networking/#i-want-to-connect-from-a-container-to-a-service-on-the-host).
`gateway.docker.internal` is a secondary address and is not implemented in all OSS alternatives to Docker Desktop (i.e. in Rancher Desktop, see https://github.com/rancher-sandbox/rancher-desktop/issues/1767).
This fixes the meta-monitoring Prometheus for users of Rancher Desktop, while also being compatible with both Docker Desktop and Podman.

Use a more well known macOS Docker host address

---

monitoring/monitoring.go

Signed-off-by: Ben Ye <benye@amazon.com>
Add back `GetMonitoringRunnable` method for the meta monitoring usecase https://github.com/thanos-io/thanos/blob/main/test/e2e/receive_test.go#L668.

Add back GetMonitoringRunnable method

---

monitoring/monitoring.go

Added option to disable cadvisor when starting e2e monitoring.
#55

Added option to disable cadvisor

---

env.go
env_docker.go
host/host.go
interactive/interactive.go
monitoring/monitoring.go

With proper detection of WSL 2 we can give it the special treatment it needs.
**On detection of WSL 2**, the following happens:
- Fail fast if cAdvisor is also enabled: it's not supported in WSL 2.
- The check for networking from container to host will listen only on `tcp4` (IPv4). I tested with `tcp` (should be IPv4 and v6) but it ended up only opening a `tcp6` port and the check happens via IPv4, which fails.
- The `hostAddr` is set to `host.docker.local`, as Windows/WSL 2 also use it.
- The `OpenInBrowser` will open the URLs in the Windows browser.
I tested this out in my Windows box and it works flawlessly.

Improve WSL 2 experience

---

Makefile
README.md
db/db.go

This improves on #58 by not needing the console port anymore and truly reflecting MinIO cluster health by definition.

Use cluster healthcheck as readiness probe for MinIO.

---

README.md
db/db.go

This PR adds an option to enable TLS for minio by generating certs, adjusting commands and readiness probes accordingly.

Add option to enable TLS for minio

---

env_docker.go

If we are running e2e tests inside Docker then it's not so straightforward to access host's network. Let's use the special `host.docker.internal` for that.

env_docker: support docker-in-docker

---

monitoring/monitoring.go

Extracted from https://github.com/thanos-io/thanos/pull/6377.
Has been useful to have this for testing systems scraping Prometheus metrics, like the Thanos Receiver, with different topologies and configurations.

Add a static metrics server

---

README.md
env.go
env_docker.go

Facilitate debugging flaky tests by providing the ability to customize --cpus parameter through environment variables.

env_docker: make --cpus customizable

---

monitoring/instrumented.go
monitoring/instrumented_composite.go
monitoring/instrumented_test.go
monitoring/metrics.go

* use the instrumented wait backoff of the instrumented runnable as default for waiting for metrics
* composite instrumented options didnt allow overwriting the backoff
* fixing the tests
This makes it possible to set the wait backoff once when creating the runnable. It is not concurrency save but i think it was not to begin with. At least `WaitRemovedMetric` also reused the instrumented runnable wait backoff already.

monitoring: use instrumented backoff as default for waiting

---

env_docker.go
env_kind.go

There are two instances where we forget to check the output of a command
when it fails. This commit ensures that we log STDOUT/STDERR in the same
way that we do whenever we capture `CombinedOutput`. Specifically, this
commit adds logging for the output when we fail to recursively chmod
the shared directory as part of the cleanup process.
One note here: recursively chmod-ing the shared directory could easily
fail if a container saves a file as root and the CI user is not root. We
might want to forget about chmod-ing and instead do a `rm -rf`, which
will delete files not owned by the user executing the command.
Signed-off-by: Lucas Servén Marín <lserven@gmail.com>

env_*: log command output

---

README.md
db/db.go

Adds Azurite blob storage and Azure cli runnable to `e2edb`.
Useful for e2e tests involving Azure objstore. 
Can use it with objstore config like,
```
type: AZURE
config:
storage_account: devstoreaccount1
storage_connection_string: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;"
container: bkt1
endpoint: 0.0.0.0:10000
```
TODO: Actually write tests with it.

Add support for Azurite object storage
